/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_authentification (void);
GtkWidget* create_gestion_des_utilisateurs (void);
GtkWidget* create_ajouter_utilisateur (void);
GtkWidget* create_rechercher_utilisateur (void);
GtkWidget* create_modifier_utilisateur (void);
GtkWidget* create_afficher_utilisateurs (void);
GtkWidget* create_supprimer_utilisateur (void);
GtkWidget* create_Acceuil_ab (void);
GtkWidget* create_Gestion_ab (void);
GtkWidget* create_Ajouter_ab (void);
GtkWidget* create_Modifier_ab (void);
GtkWidget* create_Afficher_ab (void);
GtkWidget* create_Supprimer_ab (void);
GtkWidget* create_Meilleur1_ab (void);
GtkWidget* create_Meilleur2_ab (void);
GtkWidget* create_Recherche_ab (void);
GtkWidget* create_welcome (void);
GtkWidget* create_Home_ME (void);
GtkWidget* create_AJOUTER (void);
GtkWidget* create_MODIFIER (void);
GtkWidget* create_SUPPRIMER (void);
GtkWidget* create_rupture_stock (void);
GtkWidget* create_Acceuil (void);
GtkWidget* create_AFFICHER (void);
GtkWidget* create_Authentification_bt (void);
GtkWidget* create_principale_bt (void);
GtkWidget* create_Ajout_bt (void);
GtkWidget* create_Modification_bt (void);
GtkWidget* create_Calcul_bt (void);
GtkWidget* create_Recherche_bt (void);
GtkWidget* create_page_principale (void);
GtkWidget* create_ajout_de_la_reclamation (void);
GtkWidget* create_modification_de_la_reclamation (void);
GtkWidget* create_statistique (void);
GtkWidget* create_ajtCapt (void);
GtkWidget* create_menuPrinahmed (void);
GtkWidget* create_listeAlarmes (void);
GtkWidget* create_captDefect (void);
GtkWidget* create_modfCapt (void);
GtkWidget* create_gestCapt (void);
GtkWidget* create_affichageahmed (void);
GtkWidget* create_ep_kais (void);
