/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *authentification;
  GtkWidget *gestion_des_utilisateurs;
  GtkWidget *ajouter_utilisateur;
  GtkWidget *rechercher_utilisateur;
  GtkWidget *modifier_utilisateur;
  GtkWidget *afficher_utilisateurs;
  GtkWidget *supprimer_utilisateur;
  GtkWidget *Acceuil_ab;
  GtkWidget *Gestion_ab;
  GtkWidget *Ajouter_ab;
  GtkWidget *Modifier_ab;
  GtkWidget *Afficher_ab;
  GtkWidget *Supprimer_ab;
  GtkWidget *Meilleur1_ab;
  GtkWidget *Meilleur2_ab;
  GtkWidget *Recherche_ab;
  GtkWidget *welcome;
  GtkWidget *Home_ME;
  GtkWidget *AJOUTER;
  GtkWidget *MODIFIER;
  GtkWidget *SUPPRIMER;
  GtkWidget *rupture_stock;
  GtkWidget *Acceuil;
  GtkWidget *AFFICHER;
  GtkWidget *Authentification_bt;
  GtkWidget *principale_bt;
  GtkWidget *Ajout_bt;
  GtkWidget *Modification_bt;
  GtkWidget *Calcul_bt;
  GtkWidget *Recherche_bt;
  GtkWidget *page_principale;
  GtkWidget *ajout_de_la_reclamation;
  GtkWidget *modification_de_la_reclamation;
  GtkWidget *statistique;
  GtkWidget *ajtCapt;
  GtkWidget *menuPrinahmed;
  GtkWidget *listeAlarmes;
  GtkWidget *captDefect;
  GtkWidget *modfCapt;
  GtkWidget *gestCapt;
  GtkWidget *affichageahmed;
  GtkWidget *ep_kais;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  /*authentification = create_authentification ();
  gtk_widget_show (authentification);
  gestion_des_utilisateurs = create_gestion_des_utilisateurs ();
  gtk_widget_show (gestion_des_utilisateurs);
  ajouter_utilisateur = create_ajouter_utilisateur ();
  gtk_widget_show (ajouter_utilisateur);
  rechercher_utilisateur = create_rechercher_utilisateur ();
  gtk_widget_show (rechercher_utilisateur);
  modifier_utilisateur = create_modifier_utilisateur ();
  gtk_widget_show (modifier_utilisateur);
  afficher_utilisateurs = create_afficher_utilisateurs ();
  gtk_widget_show (afficher_utilisateurs);
  supprimer_utilisateur = create_supprimer_utilisateur ();
  gtk_widget_show (supprimer_utilisateur);
  Acceuil_ab = create_Acceuil_ab ();
  gtk_widget_show (Acceuil_ab);
  Gestion_ab = create_Gestion_ab ();
  gtk_widget_show (Gestion_ab);
  Ajouter_ab = create_Ajouter_ab ();
  gtk_widget_show (Ajouter_ab);
  Modifier_ab = create_Modifier_ab ();
  gtk_widget_show (Modifier_ab);
  Afficher_ab = create_Afficher_ab ();
  gtk_widget_show (Afficher_ab);
  Supprimer_ab = create_Supprimer_ab ();
  gtk_widget_show (Supprimer_ab);
  Meilleur1_ab = create_Meilleur1_ab ();
  gtk_widget_show (Meilleur1_ab);
  Meilleur2_ab = create_Meilleur2_ab ();
  gtk_widget_show (Meilleur2_ab);
  Recherche_ab = create_Recherche_ab ();
  gtk_widget_show (Recherche_ab);*/
  welcome = create_welcome ();
  gtk_widget_show (welcome);
  /*Home_ME = create_Home_ME ();
  gtk_widget_show (Home_ME);
  AJOUTER = create_AJOUTER ();
  gtk_widget_show (AJOUTER);
  MODIFIER = create_MODIFIER ();
  gtk_widget_show (MODIFIER);
  SUPPRIMER = create_SUPPRIMER ();
  gtk_widget_show (SUPPRIMER);
  rupture_stock = create_rupture_stock ();
  gtk_widget_show (rupture_stock);
  Acceuil = create_Acceuil ();
  gtk_widget_show (Acceuil);
  AFFICHER = create_AFFICHER ();
  gtk_widget_show (AFFICHER);
  Authentification_bt = create_Authentification_bt ();
  gtk_widget_show (Authentification_bt);
  principale_bt = create_principale_bt ();
  gtk_widget_show (principale_bt);
  Ajout_bt = create_Ajout_bt ();
  gtk_widget_show (Ajout_bt);
  Modification_bt = create_Modification_bt ();
  gtk_widget_show (Modification_bt);
  Calcul_bt = create_Calcul_bt ();
  gtk_widget_show (Calcul_bt);
  Recherche_bt = create_Recherche_bt ();
  gtk_widget_show (Recherche_bt);
  page_principale = create_page_principale ();
  gtk_widget_show (page_principale);
  ajout_de_la_reclamation = create_ajout_de_la_reclamation ();
  gtk_widget_show (ajout_de_la_reclamation);
  modification_de_la_reclamation = create_modification_de_la_reclamation ();
  gtk_widget_show (modification_de_la_reclamation);
  statistique = create_statistique ();
  gtk_widget_show (statistique);
  ajtCapt = create_ajtCapt ();
  gtk_widget_show (ajtCapt);
  menuPrinahmed = create_menuPrinahmed ();
  gtk_widget_show (menuPrinahmed);
  listeAlarmes = create_listeAlarmes ();
  gtk_widget_show (listeAlarmes);
  captDefect = create_captDefect ();
  gtk_widget_show (captDefect);
  modfCapt = create_modfCapt ();
  gtk_widget_show (modfCapt);
  gestCapt = create_gestCapt ();
  gtk_widget_show (gestCapt);
  affichageahmed = create_affichageahmed ();
  gtk_widget_show (affichageahmed);
  ep_kais = create_ep_kais ();
  gtk_widget_show (ep_kais);*/

  gtk_main ();
  return 0;
}

